"""dispatcher.py - Dynamic Fan-Out generator."""
from typing import List
from langgraph.types import Send
from agent_spin_up.state import AuditGraphState

"""
    Inspects specialist_tasks generated by the Orchestrator
    and dynamically yields a Send() for each specialist.
"""
def dynamic_agent_dispatcher(state: AuditGraphState) -> List[Send]:
    tasks = state["specialist_tasks"]
    print(f"\n[Dispatcher] Spawning {len(tasks)} dynamic Send() workers concurrently...")

    return [
        Send("specialist_agent", task)
        for task in tasks
    ]
