import operator
from typing import Annotated, List, TypedDict

"""Isolated payload passed to EACH dynamically spawned specialist agent."""
class AgentTaskState(TypedDict):
    role: str           # e.g., "Security Specialist"
    focus_area: str     # e.g., "SQL Injection & Auth"
    instructions: str   # Custom prompt tailored for this agent
    code_snippet: str   # The code to audit

"""Shared state of the entire multi-agent workflow."""
class AuditGraphState(TypedDict):
    code_to_review: str
    specialist_tasks: List[dict]  # Generated by Orchestrator

    # Reducer: operator.add safely merges reports from all dynamic agents
    audit_reports: Annotated[List[dict], operator.add]

    final_report: str  # Generated by Synthesizer
